app_catalog_promotion:
    resource: |
        alias: urbanara_catalog_promotion.catalog_promotion
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        grid: urbanara_catalog_promotion_catalog_promotion
        vars:
            all:
                subheader: urbanara_catalog_promotion.ui.manage_catalog_discounts_and_promotional_campaigns
                templates:
                    form: "@CatalogPromotionPlugin/_form.html.twig"
            index:
                icon: in cart
    type: sylius.resource
