sylius_grid:
    grids:
        acme_sylius_catalog_promotion_catalog_promotion:
            driver:
                name: doctrine/orm
                options:
                    class: "%acme_sylius_catalog_promotion.model.catalog_promotion.class%"
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/nameAndDescription.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, name]
            actions:
                main:
                    create:
                        type: create
