sylius_catalog_promotion_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: SyliusCatalogPromotionBundle:Greeting:staticallyGreet
        name: ~

sylius_catalog_promotion_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: SyliusCatalogPromotionBundle:Greeting:dynamicallyGreet
        name: ~
